% Specify the model name (without .slx extension)
modelName = 'testingPlatform';

% Open the model if it is not already open
open_system(modelName);

% Define the list of Rigid Transform block names
blocks21to50 = ["Rigid Transform21", "Rigid Transform22", "Rigid Transform23", ...
                "Rigid Transform24", "Rigid Transform25", "Rigid Transform26", ...
                "Rigid Transform27", "Rigid Transform28", "Rigid Transform29", ...
                "Rigid Transform30", "Rigid Transform31", "Rigid Transform32", ...
                "Rigid Transform33", "Rigid Transform34", "Rigid Transform35", ...
                "Rigid Transform36", "Rigid Transform37", "Rigid Transform38", ...
                "Rigid Transform39", "Rigid Transform40", "Rigid Transform41", ...
                "Rigid Transform42", "Rigid Transform43", "Rigid Transform44", ...
                "Rigid Transform45", "Rigid Transform46", "Rigid Transform47", ...
                "Rigid Transform48", "Rigid Transform49", "Rigid Transform50"];

blocks1to20and51to60 = ["Rigid Transform1", "Rigid Transform2", "Rigid Transform3", ...
                        "Rigid Transform4", "Rigid Transform5", "Rigid Transform6", ...
                        "Rigid Transform7", "Rigid Transform8", "Rigid Transform9", ...
                        "Rigid Transform10", "Rigid Transform11", "Rigid Transform12", ...
                        "Rigid Transform13", "Rigid Transform14", "Rigid Transform15", ...
                        "Rigid Transform16", "Rigid Transform17", "Rigid Transform18", ...
                        "Rigid Transform19", "Rigid Transform20", ...
                        "Rigid Transform51", "Rigid Transform52", "Rigid Transform53", ...
                        "Rigid Transform54", "Rigid Transform55", "Rigid Transform56", ...
                        "Rigid Transform57", "Rigid Transform58", "Rigid Transform59", "Rigid Transform60"];

blocks61to90 = ["Rigid Transform61", "Rigid Transform62", "Rigid Transform63", ...
                "Rigid Transform64", "Rigid Transform65", "Rigid Transform66", ...
                "Rigid Transform67", "Rigid Transform68", "Rigid Transform69", ...
                "Rigid Transform70", "Rigid Transform71", "Rigid Transform72", ...
                "Rigid Transform73", "Rigid Transform74", "Rigid Transform75", ...
                "Rigid Transform76", "Rigid Transform77", "Rigid Transform78", ...
                "Rigid Transform79", "Rigid Transform80", "Rigid Transform81", ...
                "Rigid Transform82", "Rigid Transform83", "Rigid Transform84", ...
                "Rigid Transform85", "Rigid Transform86", "Rigid Transform87", ...
                "Rigid Transform88", "Rigid Transform89", "Rigid Transform90"];

blocks91to120 = ["Rigid Transform91", "Rigid Transform92", "Rigid Transform93", ...
                 "Rigid Transform94", "Rigid Transform95", "Rigid Transform96", ...
                 "Rigid Transform97", "Rigid Transform98", "Rigid Transform99", ...
                 "Rigid Transform100", "Rigid Transform101", "Rigid Transform102", ...
                 "Rigid Transform103", "Rigid Transform104", "Rigid Transform105", ...
                 "Rigid Transform106", "Rigid Transform107", "Rigid Transform108", ...
                 "Rigid Transform109", "Rigid Transform110", "Rigid Transform111", ...
                 "Rigid Transform112", "Rigid Transform113", "Rigid Transform114", ...
                 "Rigid Transform115", "Rigid Transform116", "Rigid Transform117", ...
                 "Rigid Transform118", "Rigid Transform119", "Rigid Transform120"];

% Define the grid size and offset step
gridSizeX = 5; % Number of columns
gridSizeY = 5; % Number of rows
offsetStepX = 0.01; % Horizontal offset step (X direction)
offsetStepY = 0.01; % Vertical offset step (Y direction)
xShiftRight = 0.05; % X-axis shift for the right grids
yShiftDown = 0.05; % Y-axis shift for the below grids

% Helper function to update block positions
function update_block_positions(modelName, blockList, xOffsetBase, yOffsetBase,offsetStepX,offsetStepY, gridSizeX)
    rowIndex = 0;
    colIndex = 0;
    for i = 1:length(blockList)
        blockPath = strcat(modelName, '/', blockList(i));
        xOffset = xOffsetBase + colIndex * offsetStepX;
        yOffset = yOffsetBase + rowIndex * offsetStepY;
        try
            set_param(blockPath, 'TranslationCartesianOffset', ['[', num2str(xOffset), ' ', num2str(yOffset), ' 0]']);
        catch ME
            warning('Could not update Rigid Transform block: %s\nError: %s', blockList(i), ME.message);
        end
        colIndex = colIndex + 1;
        if colIndex >= gridSizeX
            colIndex = 0;
            rowIndex = rowIndex + 1;
        end
    end
end

% Update positions for each set
update_block_positions(modelName, blocks21to50, 0, 0, offsetStepX,offsetStepY, gridSizeX); % Original grid
update_block_positions(modelName, blocks1to20and51to60, 0, yShiftDown,offsetStepX,offsetStepY, gridSizeX); % Below original grid
update_block_positions(modelName, blocks61to90, xShiftRight, 0, offsetStepX,offsetStepY, gridSizeX); % Right of original grid
update_block_positions(modelName, blocks91to120, xShiftRight, yShiftDown, offsetStepX,offsetStepY, gridSizeX); % Right and below

disp('All Rigid Transform offsets have been updated.');
